# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nlozMZ2smcFG6E2lm-gUmNhf6G2hUf6
"""

import numpy as np
import matplotlib.pyplot as plt

def model_acc_loss(train_acc, test_acc, train_loss, test_loss):
    fig, axs = plt.subplots(1,2,figsize=(25,6))
    size_ep = len(train_acc)
    legends = ['train', 'test']

    axs[0].plot(range(1,size_ep+1), train_acc)
    axs[0].plot(range(1,size_ep+1), test_acc)
    axs[0].set_ylabel('Accuracy')
    axs[0].set_xlabel('Epoch')
    axs[0].set_xticks(np.arange(1,size_ep+1),size_ep/10)
    axs[0].legend(legends, loc='best')

   # plot losses
    axs[1].plot(range(1,size_ep+1),train_loss)
    axs[1].plot(range(1,size_ep+1),test_loss)
    axs[1].set_ylabel('Loss')
    axs[1].set_xlabel('Epoch')
    axs[1].set_xticks(np.arange(1,size_ep+1),size_ep/10)
    axs[1].legend(legends, loc='best')
    plt.show()